### ISSUE TITLE
Grass Block

### ISSUE THREAD

**Issue by softyay** [Capstone-System-Miami/Artwork#7]

**Comment by OskarFinneran** [comment]
![Grass block](https://github.com/user-attachments/assets/290c0b3e-7bcc-45f2-9b2e-ab32301f5df4)
![Grass block border](https://github.com/user-attachments/assets/a6809bd6-0737-4591-9b76-31ba84adca13)

I tried to resize and upload the files here on github but it wouldn't allow me for some reason.

**Comment by softyay** [comment]
So what you'll want to do here is like what we did for the tutorial, just without Unity.  If you clone the repository, then save your image files to that folder on your computer, you can commit and push those changes, and then we can all have access to the folder!  "Repository" is kind of just a fancy word for "folder"

**Comment by OskarFinneran** [comment]
sure thing doing it right now
